<?php
/**
 * @var $block \Anyday\Payment\Block\Catalog\Product\Pricetag
 */
?>
<?php if ($block->isEnabled()): ?>
    <div class="adtag-info" style="<?= /* @noEscape */ $block->getInlineCss(); ?>" data-bind="scope: 'adtag-component'">
        <anyday-price-tag style="display: block;" data-bind="visible: visibleTagElement"
                          total-price="<?= /* @noEscape */ $block->getPrice(); ?>"
                          price-tag-token="<?= /* @noEscape */ $block->getTagCode(); ?>"
                          currency="<?= /* @noEscape */ $block->getCurrency(); ?>"
                          environment="production" type="module">
        </anyday-price-tag>
    </div>

    <script>
        window.anydaytag = <?= /* @noEscape */ $block->getSerializedTagConfig(); ?>;
    </script>
    <script type="text/x-magento-init">
       {
           "*": {
               "Magento_Ui/js/core/app": {
                   "components": {
                       "adtag-component": {
                           "component": "Anyday_Payment/js/view/product/price_tag"
                       }
                   }
               }
           },
           "head": {
                "<?= $block->getPricetagLanguage() ?>" : {}
            }
       }
    </script>
<?php endif; ?>
